/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/Hair2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hair2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.01, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
        <mesh geometry={nodes.Imani_Scalp_254252.geometry} material={materials.Scalp} />
        <mesh geometry={nodes.Imani_Scalp_254252_1.geometry} material={materials['Braid MAT 3']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Hair2.gltf')
