/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/nadu_hair/scene.gltf
Author: backdoor3d (https://sketchfab.com/backdoor3d)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/nadu-hair-f94120eeb3f442eb853e60602501cf82
Title: nadu Hair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nadu_hair/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bangs} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BangsCross} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.BangsStrands} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.CrossStrands} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Hair} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Strands} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Scalp} />
      </group>
    </group>
  )
}

useGLTF.preload('/nadu_hair/scene.gltf')
